version: '3.9'

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/duckbill
    depends_on:
      - mongo

  frontend:
    build:
      context: ./duckbills
      dockerfile: frontend.dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data:
